slam_toolbox:
  ros__parameters:

    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    use_map_saver: true
    mode: mapping #localization

    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02 #if 0 never publishes odometry
    map_update_interval: 2.0  # Reduced for more frequent updates
    resolution: 0.05
    
    # LDS-02 LiDAR specifications: min_range=0.01m, max_range=5.0m
    min_laser_range: 0.01  # Very small to capture close obstacles
    max_laser_range: 5.0  # Adjusted for LDS-02 maximum range
    
    minimum_time_interval: 0.1  # Reduced for more frequent processing
    transform_timeout: 0.2
    tf_buffer_duration: 30.
    stack_size_to_use: 40000000 #// program needs a larger stack size to serialize large maps
    enable_interactive_mode: true

    # General Parameters - More sensitive for hand-held LiDAR scanning
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.01  # Very small - 1cm instead of 30cm
    minimum_travel_heading: 0.01   # Very small - ~0.6 degrees instead of 17 degrees
    scan_buffer_size: 20  # Increased buffer for better matching
    scan_buffer_maximum_scan_distance: 5.0  # Match max_laser_range
    link_match_minimum_response_fine: 0.05  # More sensitive matching
    link_scan_maximum_distance: 2.0  # Increased for better scan matching
    loop_search_maximum_distance: 3.0  # Reduced to fit within LDS-02 range
    do_loop_closing: true 
    loop_match_minimum_chain_size: 5  # Reduced for easier loop closure          
    loop_match_maximum_variance_coarse: 2.0  # More permissive
    loop_match_minimum_response_coarse: 0.2  # More sensitive    
    loop_match_minimum_response_fine: 0.3  # More sensitive

    # Correlation Parameters - More sensitive correlation
    correlation_search_space_dimension: 0.8  # Increased search space
    correlation_search_space_resolution: 0.005  # Higher resolution
    correlation_search_space_smear_deviation: 0.05  # Reduced smearing

    # Correlation Parameters - Loop Closure Parameters
    loop_search_space_dimension: 5.0  # Reduced to fit within LDS-02 range
    loop_search_space_resolution: 0.02  # Higher resolution
    loop_search_space_smear_deviation: 0.02  # Reduced smearing

    # Scan Matcher Parameters - More aggressive scan matching
    distance_variance_penalty: 0.3  # Reduced penalty for distance variance    
    angle_variance_penalty: 0.5  # Reduced penalty for angle variance   

    fine_search_angle_offset: 0.00349     
    coarse_search_angle_offset: 0.349   
    coarse_angle_resolution: 0.0174  # Higher resolution (1 degree)       
    minimum_angle_penalty: 0.5  # Reduced penalty
    minimum_distance_penalty: 0.3  # Reduced penalty
    use_response_expansion: true 