/**:
  turtlebot3_node:
    ros__parameters:

      enable_stamped_cmd_vel: false

      opencr:
        id: 200
        baud_rate: 1000000
        protocol_version: 2.0

      wheels:
        separation: 0.24
        radius: 0.035

      limits:
        max_velocity: 0.1     # Max linear velocity (m/s) - Real robot specs
        max_rpm: 27           # Max motor RPM - Real robot specs

      motors:
        profile_acceleration_constant: 100.0

        # [rev/min2] - Reduced for slower robot (Max 27 RPM, 0.1 m/s)
        # ref) http://emanual.robotis.com/docs/en/dxl/x/xl430-w250/#profile-acceleration
        profile_acceleration: 0.0

      sensors:
        bumper_1: 0
        bumper_2: 0
        illumination: 0
        ir: 0
        sonar: 0
/**:
  diff_drive_controller:
    ros__parameters:

      odometry:
        publish_tf: true
        use_imu: true
        frame_id: "odom"
        child_frame_id: "base_footprint"
